# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 79c2af700c764111df544c2b23cbf4fdc0b57d259f1014b9a1c966768fa1bedb8627a7ba3badce8675a87d0ed5ea6e66367f71bedfdc7680ba1a129f57ddc3f6

test:
  secret_key_base: 3314dd3afb83496a1e2da87566eb62fe17608bd146d1d73025ac2dc95f02ce46deccfe5d5c237ef378007459eec05f1b546acf6a49d9350f7314a0ff418f796a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
